# Generated by Django 6.0.5 on 2026-06-04 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ODS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('LING', 'Linguagem'), ('BD', 'Banco de Dados'), ('DESIGN', 'Design/Ferramenta')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('ALUNO', 'Aluno/Egresso'), ('PROFESSOR', 'Professor Orientador'), ('ADMIN', 'Administrador'), ('PARCEIRO', 'Organização Parceira')], default='ALUNO', max_length=20)),
                ('curso', models.CharField(blank=True, max_length=100, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('nome_organizacao', models.CharField(blank=True, max_length=150, null=True)),
                ('setor_atuacao', models.CharField(blank=True, max_length=100, null=True)),
                ('LinkedIn', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, max_length=100, null=True)),
                ('instagram', models.URLField(blank=True, max_length=100, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil_fotos/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('setores_relacionados', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('NOVA', 'Nova Demanda'), ('VALIDADA', 'Tema Validado'), ('DESENVOLVIMENTO', 'Em Desenvolvimento'), ('ENTREGUE', 'Solução Entregue')], default='NOVA', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ods_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos.ods')),
                ('organizacao', models.ForeignKey(limit_choices_to={'tipo_usuario': 'PARCEIRO'}, on_delete=django.db.models.deletion.CASCADE, to='projetos.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('semestre', models.CharField(max_length=10)),
                ('resumo', models.TextField()),
                ('inspiracao', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('documentacao_pdf', models.FileField(blank=True, null=True, upload_to='documentos_projetos/')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('REVISAO', 'Em revisão'), ('AJUSTES', 'Pendente de Ajustes'), ('APROVADO', 'Aprovado')], default='RASCUNHO', max_length=20)),
                ('nota_conceito', models.CharField(blank=True, max_length=10, null=True)),
                ('feedback_professor', models.TextField(blank=True, null=True)),
                ('Link_repositorio', models.URLField(blank=True, null=True)),
                ('Link_prototipo', models.URLField(blank=True, null=True)),
                ('link_demo', models.URLField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autores', models.ManyToManyField(related_name='projetos', to='projetos.perfil')),
                ('ods', models.ManyToManyField(blank=True, to='projetos.ods')),
                ('tecnologias', models.ManyToManyField(blank=True, to='projetos.tecnologia')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='projetos_galeria/')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='projetos.projeto')),
            ],
        ),
    ]
