# Generated by Django 6.0.6 on 2026-06-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
