# Generated by Django 6.0.5 on 2026-06-16 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_turma_perfil_turma_projeto_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='ods',
            field=models.ManyToManyField(blank=True, related_name='demandas_ods', to='projetos.ods'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='parceiro',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='demanda',
            name='semestre',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='organizacao',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'PARCEIRO'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.perfil'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='setores_relacionados',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='status',
            field=models.CharField(choices=[('NOVA', 'Nova Demanda'), ('VALIDADA', 'Tema Validado'), ('DESENVOLVIMENTO', 'Em Desenvolvimento'), ('ENTREGUE', 'Soluções Entregues')], default='NOVA', max_length=20),
        ),
    ]
